In [4]:
from tqdm import tqdm
import json
from PIL import Image
import pandas as pd

In [12]:
lines = ''
root_dir = '\\\\databrick\\Active Server Drive\\log_dir\\eve_miner'
with open(f"{root_dir}\\miner_2023-03-12_21-07-53_629091.log") as f:
    lines = f.readlines()

In [13]:
class_lines = []
for line in tqdm(lines):
    if 'Current Screen Classification:' in line or 'Current Screen:' in line:
        index = line.find('{')
        class_lines.append(json.loads(line[index:-1].replace("'", '"').replace('UUID("', '"').replace('")', '"').replace("True", '1').replace("False", '0')))

100%|███████████████████████████████████████████████████████████████████████| 32458/32458 [00:00<00:00, 2818023.58it/s]

In [14]:
len(class_lines)

453

In [15]:
class_lines[0]

{'argmax_index': 2,
 'value_at_argmax': 0.9999945,
 'pass_general_tollerance': 1,
 'class': 'in_flight',
 'classes': ['char_select', 'connection_lost', 'in_flight', 'in_hanger'],
 'scores': [6.320475449683727e-07,
  2.6765549137053313e-06,
  0.9999945163726807,
  2.212868594142492e-06],
 'id': '37243116-c144-11ed-b55d-9c5c8ec2126c',
 'model': 'game_state'}

In [16]:
df = pd.DataFrame(class_lines)
df

,argmax_index,value_at_argmax,pass_general_tollerance,class,classes,scores,id,model
0,2,0.999995,1,in_flight,"[char_select, connection_lost, in_flight, in_h...","[6.320475449683727e-07, 2.6765549137053313e-06...",37243116-c144-11ed-b55d-9c5c8ec2126c,game_state
1,2,0.999994,1,in_flight,"[char_select, connection_lost, in_flight, in_h...","[6.599354378522548e-07, 2.7770145152317127e-06...",3924e4aa-c144-11ed-a004-9c5c8ec2126c,game_state
2,2,0.999999,1,in_flight,"[char_select, connection_lost, in_flight, in_h...","[1.2401969229358656e-07, 3.1946731837706466e-0...",6252df50-c144-11ed-8793-9c5c8ec2126c,game_state
3,2,0.999998,1,in_flight,"[char_select, connection_lost, in_flight, in_h...","[1.6080845455235249e-07, 2.751196177541715e-07...",8bca6f86-c144-11ed-8e9e-9c5c8ec2126c,game_state
4,2,0.999999,1,in_flight,"[char_select, connection_lost, in_flight, in_h...","[1.6534809788026905e-07, 2.7607009656094306e-0...",b4eaff56-c144-11ed-a669-9c5c8ec2126c,game_state
...,...,...,...,...,...,...,...,...
448,2,0.999994,1,in_flight,"[char_select, connection_lost, in_flight, in_h...","[1.2782240901287878e-06, 4.0435094206259237e-0...",8b71f009-c1e9-11ed-b807-9c5c8ec2126c,game_state
449,3,0.999431,1,in_hanger,"[char_select, connection_lost, in_flight, in_h...","[8.368658654944738e-07, 1.2096114915038925e-05...",a1b32bd7-c1ee-11ed-b844-9c5c8ec2126c,game_state
450,2,0.999999,1,in_flight,"[char_select, connection_lost, in_flight, in_h...","[1.3776873686310864e-07, 1.1144653910832858e-0...",c95950bd-c1ee-11ed-8dd8-9c5c8ec2126c,game_state
451,2,1.000000,1,in_flight,"[char_select, connection_lost, in_flight, in_h...","[1.3151283440038242e-07, 6.636831528794573e-08...",cbaa274b-c1ee-11ed-ac5a-9c5c8ec2126c,game_state
452,2,0.999991,1,in_flight,"[char_select, connection_lost, in_flight, in_h...","[1.9225753931095824e-06, 4.579696053497173e-07...",f4e320e4-c1ee-11ed-8366-9c5c8ec2126c,game_state

In [17]:
df = df.sort_values(by='value_at_argmax', ascending=True).reset_index()
del df['index']
df

,argmax_index,value_at_argmax,pass_general_tollerance,class,classes,scores,id,model
0,3,0.998762,1,in_hanger,"[char_select, connection_lost, in_flight, in_h...","[1.4346460375236347e-06, 2.058779136859812e-05...",5043c58b-c150-11ed-9f50-9c5c8ec2126c,game_state
1,3,0.998764,1,in_hanger,"[char_select, connection_lost, in_flight, in_h...","[1.458392489439575e-06, 2.0365489035611972e-05...",b3211d34-c188-11ed-80f4-9c5c8ec2126c,game_state
2,3,0.998769,1,in_hanger,"[char_select, connection_lost, in_flight, in_h...","[1.438098820472078e-06, 2.0419447537278756e-05...",aaf50eb9-c157-11ed-ba4c-9c5c8ec2126c,game_state
3,3,0.998773,1,in_hanger,"[char_select, connection_lost, in_flight, in_h...","[1.4453297580985236e-06, 1.9954595700255595e-0...",37700db8-c155-11ed-8bdc-9c5c8ec2126c,game_state
4,3,0.998777,1,in_hanger,"[char_select, connection_lost, in_flight, in_h...","[1.3852986739948392e-06, 2.043873246293515e-05...",dd1f48b3-c14d-11ed-86b6-9c5c8ec2126c,game_state
...,...,...,...,...,...,...,...,...
448,2,1.000000,1,in_flight,"[char_select, connection_lost, in_flight, in_h...","[1.0018534624123276e-07, 7.221629516607209e-08...",8b933f07-c166-11ed-a554-9c5c8ec2126c,game_state
449,2,1.000000,1,in_flight,"[char_select, connection_lost, in_flight, in_h...","[1.3196725490161043e-07, 9.855595806129713e-08...",390eaa15-c1b0-11ed-854d-9c5c8ec2126c,game_state
450,2,1.000000,1,in_flight,"[char_select, connection_lost, in_flight, in_h...","[1.3151283440038242e-07, 6.636831528794573e-08...",cbaa274b-c1ee-11ed-ac5a-9c5c8ec2126c,game_state
451,2,1.000000,1,in_flight,"[char_select, connection_lost, in_flight, in_h...","[7.398372758871119e-08, 4.648781271043845e-08,...",a7d386e6-c1b7-11ed-8b5e-9c5c8ec2126c,game_state
452,2,1.000000,1,in_flight,"[char_select, connection_lost, in_flight, in_h...","[1.1372122088459946e-07, 5.457028606770109e-08...",070b8000-c14e-11ed-99df-9c5c8ec2126c,game_state

In [ ]:
import matplotlib.pyplot as plt
for i in df[0:5].index:
    im = Image.open(f"{root_dir}\\images\\{df.loc[i, 'id']}.png")
    plt.figure()
    plt.title(df.loc[i, 'class'] + ' ' + str(df.loc[i, 'value_at_argmax']))
    plt.imshow(im)

In [11]:
low_performing_list = df[df['value_at_argmax']<=.999]['id'].tolist()
low_performing_list
#Image.open(f"{root_dir}\\{df[0:2]['id'].tolist()[0]}.png")

['e070aa60-c135-11ed-8dbe-9c5c8ec2126c',
 '6d6c2e8a-c133-11ed-aead-9c5c8ec2126c']

In [23]:
#import shutil
#for item in low_performing_list:
    #shutil.move(f"{root_dir}\\images\\{item}.png", f"O:\\source\\repos\\EVE-Online-Bot\\training_data\\unclass\\{item}.png")