In [4]:
from tqdm import tqdm
import json
from PIL import Image
import pandas as pd

In [5]:
lines = ''
root_dir = '\\\\databrick\\Active Server Drive\\log_dir\\eve_miner'
with open(f"{root_dir}\\miner_2023-03-12_10-21-03_089813.log") as f:
    lines = f.readlines()

In [6]:
class_lines = []
for line in tqdm(lines):
    if 'Current Screen Classification:' in line or 'Current Screen:' in line:
        index = line.find('{')
        class_lines.append(json.loads(line[index:-1].replace("'", '"').replace('UUID("', '"').replace('")', '"').replace("True", '1').replace("False", '0')))

100%|████████████████████████████████████████████████████████████████████████| 20103/20103 [00:00<00:00, 478661.25it/s]

In [7]:
len(class_lines)

82

In [8]:
class_lines[0]

{'argmax_index': 2,
 'value_at_argmax': 0.9999895,
 'pass_general_tollerance': 1,
 'class': 'in_flight',
 'classes': ['char_select', 'connection_lost', 'in_flight', 'in_hanger'],
 'scores': [1.2346841913313256e-06,
  8.371470698875783e-07,
  0.9999895095825195,
  8.482822522637434e-06],
 'id': 'd491e1ba-c0e9-11ed-9f9e-9c5c8ec2126c',
 'model': 'game_state'}

In [9]:
df = pd.DataFrame(class_lines)
df

,argmax_index,value_at_argmax,pass_general_tollerance,class,classes,scores,id,model
0,2,0.999989,1,in_flight,"[char_select, connection_lost, in_flight, in_h...","[1.2346841913313256e-06, 8.371470698875783e-07...",d491e1ba-c0e9-11ed-9f9e-9c5c8ec2126c,game_state
1,2,0.999990,1,in_flight,"[char_select, connection_lost, in_flight, in_h...","[1.1531001291587017e-06, 7.908183761173859e-07...",d6dedefc-c0e9-11ed-a475-9c5c8ec2126c,game_state
2,3,0.999389,1,in_hanger,"[char_select, connection_lost, in_flight, in_h...","[7.146942948565993e-07, 1.2595268344739452e-05...",7742f3ce-c0f0-11ed-abbb-9c5c8ec2126c,game_state
3,2,0.999999,1,in_flight,"[char_select, connection_lost, in_flight, in_h...","[9.321090743696914e-08, 8.421931596558352e-08,...",9ede6c0c-c0f0-11ed-a1c6-9c5c8ec2126c,game_state
4,2,0.999999,1,in_flight,"[char_select, connection_lost, in_flight, in_h...","[9.227587582927299e-08, 7.344018371213679e-08,...",a123cb26-c0f0-11ed-a0b4-9c5c8ec2126c,game_state
...,...,...,...,...,...,...,...,...
77,2,0.999991,1,in_flight,"[char_select, connection_lost, in_flight, in_h...","[1.8233107539344928e-06, 6.358559403452091e-07...",3427e068-c135-11ed-9230-9c5c8ec2126c,game_state
78,3,0.998871,1,in_hanger,"[char_select, connection_lost, in_flight, in_h...","[1.2918903848913033e-06, 2.0495292119449005e-0...",e070aa60-c135-11ed-8dbe-9c5c8ec2126c,game_state
79,2,0.999999,1,in_flight,"[char_select, connection_lost, in_flight, in_h...","[1.260244175682601e-07, 1.3698371503778617e-07...",07f61e33-c136-11ed-82a7-9c5c8ec2126c,game_state
80,2,0.999999,1,in_flight,"[char_select, connection_lost, in_flight, in_h...","[9.206737416889155e-08, 1.0145836171204792e-07...",0a4569d5-c136-11ed-be22-9c5c8ec2126c,game_state
81,2,0.999992,1,in_flight,"[char_select, connection_lost, in_flight, in_h...","[1.4679280866403133e-06, 6.324164019133605e-07...",337fc107-c136-11ed-9b10-9c5c8ec2126c,game_state

In [10]:
df = df.sort_values(by='value_at_argmax', ascending=True).reset_index()
del df['index']
df

,argmax_index,value_at_argmax,pass_general_tollerance,class,classes,scores,id,model
0,3,0.998871,1,in_hanger,"[char_select, connection_lost, in_flight, in_h...","[1.2918903848913033e-06, 2.0495292119449005e-0...",e070aa60-c135-11ed-8dbe-9c5c8ec2126c,game_state
1,3,0.998907,1,in_hanger,"[char_select, connection_lost, in_flight, in_h...","[1.3136938150637434e-06, 2.0366815078887157e-0...",6d6c2e8a-c133-11ed-aead-9c5c8ec2126c,game_state
2,3,0.999315,1,in_hanger,"[char_select, connection_lost, in_flight, in_h...","[7.459913717866584e-07, 1.462861655454617e-05,...",35557fe0-c126-11ed-b974-9c5c8ec2126c,game_state
3,3,0.999358,1,in_hanger,"[char_select, connection_lost, in_flight, in_h...","[7.375668928943924e-07, 1.3948809282737784e-05...",1f251a46-c128-11ed-8c32-9c5c8ec2126c,game_state
4,3,0.999370,1,in_hanger,"[char_select, connection_lost, in_flight, in_h...","[7.559444270555105e-07, 1.4660117813036777e-05...",53a0a05e-c12e-11ed-b3b6-9c5c8ec2126c,game_state
...,...,...,...,...,...,...,...,...
77,2,0.999999,1,in_flight,"[char_select, connection_lost, in_flight, in_h...","[8.453058342183795e-08, 5.725246055021671e-08,...",9bb188a0-c0f8-11ed-8f70-9c5c8ec2126c,game_state
78,2,0.999999,1,in_flight,"[char_select, connection_lost, in_flight, in_h...","[9.227587582927299e-08, 7.344018371213679e-08,...",a123cb26-c0f0-11ed-a0b4-9c5c8ec2126c,game_state
79,2,1.000000,1,in_flight,"[char_select, connection_lost, in_flight, in_h...","[9.591678917786339e-08, 6.617113257334495e-08,...",c130b86c-c132-11ed-9586-9c5c8ec2126c,game_state
80,2,1.000000,1,in_flight,"[char_select, connection_lost, in_flight, in_h...","[1.0564056651674036e-07, 6.419204368057763e-08...",2ad296c6-c113-11ed-a59e-9c5c8ec2126c,game_state
81,2,1.000000,1,in_flight,"[char_select, connection_lost, in_flight, in_h...","[1.2050745112901495e-07, 1.0030446873088295e-0...",5634e733-c12c-11ed-bd7f-9c5c8ec2126c,game_state

In [45]:
import matplotlib.pyplot as plt
for i in df[0:5].index:
    im = Image.open(f"{root_dir}\\images\\{df.loc[i, 'id']}.png")
    plt.figure()
    plt.title(df.loc[i, 'class'] + ' ' + str(df.loc[i, 'value_at_argmax']))
    plt.imshow(im)

In [11]:
low_performing_list = df[df['value_at_argmax']<=.999]['id'].tolist()
low_performing_list
#Image.open(f"{root_dir}\\{df[0:2]['id'].tolist()[0]}.png")

['e070aa60-c135-11ed-8dbe-9c5c8ec2126c',
 '6d6c2e8a-c133-11ed-aead-9c5c8ec2126c']

In [23]:
#import shutil
#for item in low_performing_list:
    #shutil.move(f"{root_dir}\\images\\{item}.png", f"O:\\source\\repos\\EVE-Online-Bot\\training_data\\unclass\\{item}.png")