In [1]:
from tqdm import tqdm
import json
from PIL import Image
import pandas as pd

In [54]:
lines = ''
root_dir = '\\\\databrick\\Active Server Drive\\log_dir\\eve_miner'
with open(f"{root_dir}\\miner_2023-03-11_18-35-13_965715.log") as f:
    lines = f.readlines()

In [60]:
class_lines = []
for line in tqdm(lines):
    if 'Current Screen Classification:' in line or 'Current Screen:' in line:
        index = line.find('{')
        class_lines.append(json.loads(line[index:-1].replace("'", '"').replace('UUID("', '"').replace('")', '"').replace("True", '1').replace("False", '0')))

100%|██████████████████████████████████████████████████████████████████████████████████████████| 14/14 [00:00<?, ?it/s]

In [61]:
len(class_lines)

1

In [62]:
class_lines[0]

{'argmax_index': 3,
 'value_at_argmax': 0.99873406,
 'pass_general_tollerance': 1,
 'class': 'in_hanger',
 'classes': ['char_select', 'connection_lost', 'in_flight', 'in_hanger'],
 'scores': [1.3366079656407237e-06,
  1.99667556444183e-05,
  0.0012445796746760607,
  0.9987340569496155],
 'id': '155024eb-c06e-11ed-93a0-9c5c8ec2126c',
 'model': 'game_state'}

In [63]:
df = pd.DataFrame(class_lines)
df

,argmax_index,value_at_argmax,pass_general_tollerance,class,classes,scores,id,model
0,3,0.998734,1,in_hanger,"[char_select, connection_lost, in_flight, in_h...","[1.3366079656407237e-06, 1.99667556444183e-05,...",155024eb-c06e-11ed-93a0-9c5c8ec2126c,game_state

In [64]:
df = df.sort_values(by='value_at_argmax', ascending=True).reset_index()
del df['index']
df

,argmax_index,value_at_argmax,pass_general_tollerance,class,classes,scores,id,model
0,3,0.998734,1,in_hanger,"[char_select, connection_lost, in_flight, in_h...","[1.3366079656407237e-06, 1.99667556444183e-05,...",155024eb-c06e-11ed-93a0-9c5c8ec2126c,game_state

In [67]:
low_performing_list = df[df['value_at_argmax']<=1]['id'].tolist()
low_performing_list
#Image.open(f"{root_dir}\\{df[0:2]['id'].tolist()[0]}.png")

['155024eb-c06e-11ed-93a0-9c5c8ec2126c']

In [68]:
import shutil
for item in low_performing_list:
    shutil.move(f"{root_dir}\\{item}.png", f"O:\\source\\repos\\EVE-Online-Bot\\training_data\\unclass\\{item}.png")